blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blog/<int:author_id>', views.blog_index, name='blog_index'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('post-create/', views.post_modify, name='post_create'),
    path('post-update/<int:id>/', views.post_modify, name='post_update'),
    path('post-safe-delete/<int:id>/', views.post_safe_delete, name='post_safe_delete'),
    path('about.html', views.about, name='about'),
    path('contact.html', views.contact, name='contact'),
    path('styles.html', views.feature, name='feature'),
]

blog/models.py
import markdown
from django.utils.html import strip_tags

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    """
    博客的分类模型
    """
    name = models.CharField(max_length=100)
    # 分类摘要
    excerpt = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    博客的标签模型
    """
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    博客的文章模型
    """

    # 文章标题
    title = models.CharField('标题', max_length=70)

    # 文章正文，使用 TextField 来存储大段文本。
    body = models.TextField('正文')

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')

    # 文章摘要
    excerpt = models.CharField('摘要', max_length=200, blank=True)

    # 文章分类与标签，分类与标签的模型已经定义在上面
    category = models.ForeignKey(
        Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是
    # django 为我们已经写好的用户模型。
    author = models.ForeignKey(
        User, verbose_name='作者', on_delete=models.CASCADE)

    # 新增 views 字段记录阅读量
    # editable=False表示不允许通过后台设置这一数据
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        """
        :param args:
        :param kwargs:
        修改文章时更新modified_time
        """
        self.modified_time = timezone.now()

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """
        返回博客详情页的绝对url
        """
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        """
        将访问次数加一并更新数据库
        """
        self.views += 1
        self.save(update_fields=['views'])

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    """
    博客文章对应的表单类
    """

    class Meta:
        model = Post
        fields = ['title', 'body']  # 定义表单包含的字段

blog/views.py
import re

import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension, slugify

from .forms import PostForm
from .models import Category, Tag, Post


# Create your views here.
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 3
    ordering = ['-created_time']

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['post_list'] = Post.objects.all()
        context['category_list'] = Category.objects.all().order_by('-id')
        return context


@login_required(login_url='/userprofile/login')
def blog_index(request, author_id=None):
    if author_id:
        post_list = Post.objects.filter(author_id=author_id)
    else:
        post_list = Post.objects.all().order_by('-created_time')

    paginator = Paginator(post_list.order_by('-created_time'), 3)
    page = request.GET.get('page')

    post_list = paginator.get_page(page)

    return render(request, 'blog/blog.html', context={"post_list": post_list})


class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 3

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        self.object_list = Post.objects.filter(category_id=cate.id)
        context = super().get_context_data(**kwargs)
        return context


class TagView(ListView):
    model = Tag
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        temp_tags = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return Post.objects.filter(tags=temp_tags)


class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，需要将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),

            'pymdownx.arithmatex',  # 使用Mathjax渲染网页
        ])
        post.body = md.convert(post.body)

        # 判断是否有目录结构
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''

        return post


@login_required(login_url='/userprofile/login')
def post_modify(request, id=None):
    # 判断用户是否请求提交数据
    if not request.user.has_perm('blog.add_post'):
        return HttpResponse("抱歉!你无权发布文章!具体请在主页联系M010K!")

    if request.method == "POST":
        post_form = PostForm(data=request.POST)

        # 判断用户提交的数据是否合法
        if post_form.is_valid():
            # 判断是更新还是新建文章
            if id:
                post = Post.objects.get(id=id)
                if request.user != post.author:
                    return HttpResponse("抱歉!你不是本文的作者，无权修改本文!")
                post.title = request.POST['title']
                post.body = request.POST['body']
            else:
                post = post_form.save(commit=False)
                post.author = request.user

            cate_id = request.POST['category']
            if not cate_id:
                return HttpResponse("文章分类不能为空!")

            if str(cate_id).isdigit():    # 文章分类为整数
                cate = Category.objects.get(id=cate_id)
                if cate:    # 是已有的文章分类
                    post.category = Category.objects.get(id=request.POST['category'])
                else:   # 文章分类名字为数字，创建对应分类
                    post.category = Category.objects.create(name=cate_id)
            else:   # 文章分类名字不是纯数字，创建对应分类
                post.category = Category.objects.create(name=cate_id)

            post.save()

            return redirect("blog:index")  # 发布完成后返回到Home页面
        # 用户请求获取数据
    else:
        post_form = PostForm()
        categories = Category.objects.all()
        tags = Tag.objects.all()
        context = {
            "post": Post.objects.get(id=id) if id else None,
            "post_form": post_form,
            "categories": categories,
            "tags": tags
        }

        if id:
            return render(request, 'blog/post_update.html', context=context)
        else:
            return render(request, 'blog/post.html', context=context)


@login_required(login_url='/userprofile/login')
def post_safe_delete(request, id):
    if request.method == "POST":
        post = Post.objects.get(id=id)
        if request.user != post.author:
            return HttpResponse("抱歉!你不是本文的作者，无权删除本文!")
        post.delete()
        return redirect('blog:index')
    else:
        return HttpResponse("删除文章仅允许Post请求!")


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    return render(request, 'blog/contact.html')


def feature(request):
    return render(request, 'blog/styles.html')


def archive(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

templates/blog/about.html
{% extends 'base.html' %} {% load static %} {% block main %}

    <!-- Page Title
       ================================================== -->
    <div id="page-title">

        <div class="row">

            <div class="ten columns centered text-center">
                <h1>About M010K</h1>
                <p>假装是全栈工程师（雾）</p>
            </div>

        </div>

    </div>
    <!-- Page Title End-->

    <!-- Content
       ================================================== -->
    <div class="content-outer">

        <div id="page-content" class="row page">

            <div id="primary" class="eight columns">

                <section>

                    <h1 align="center">M010K</h1>

                    <!-- <p class="lead">Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum
                        velit. </p>

                    <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum
                        velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. </p> -->

                    <div class="row">

                        <div class="introduction" align="center">

                            <div class="member-name">
                            </div>

                            <img src="{% static 'blog/images/team/index_400_400.png' %}" alt=""/>

                            <p>哈尔滨工业大学（威海）<br>计算机科学与技术专业 大三 <br>
                            </p>


                        </div>

                        <!-- Team wrapper End -->

                    </div>
                    <!-- row End -->

                </section>
                <!-- section end -->

            </div>
            <!-- primary end -->

            <div id="secondary" class="four columns end">

                <aside id="sidebar">

                    <div class="widget widget_search">
                        <h5>Search</h5>
                        <form action="#">

                            <input class="text-search" type="text"
                                   onfocus="if (this.value == 'Search here...') { this.value = ''; }"
                                   onblur="if(this.value == '') { this.value = 'Search here...'; }"
                                   value="Search here...">
                            <input type="submit" class="submit-search" value="">

                        </form>
                    </div>

                    <div class="widget widget_text">
                        {% if post.toc %}
                            <h5 class="widget-title">文章目录</h5>
                            <div class="textwidget">{{ post.toc|safe }}</div>
                        {% else %}
                            <h5 class="widget-title">Tenet</h5>
                            <div class="textwidget">When in doubt, use brute force. ——Ken Thompson</div>

                        {% endif %}

                    </div>

                    <div class="widget widget_contact">
                        <h5>Address and Phone</h5>
                        <p class="address">
                            山东省 威海市<br> 哈尔滨工业大学（威海） <br>
                        </p>

                        <h5>Email and Social</h5>
                        <p>
                            E-mail: 1223987303@qq.com<br> Github: <a href="https://github.com/M010K">@Github</a><br>
                            CSDN: <a href="https://blog.csdn.net/qq_43444349">M010K的博客</a>
                        </p>
                    </div>

                </aside>

            </div>
            <!-- secondary End-->

        </div>
        <!-- page-content End-->

    </div>
    <!-- Content End-->
{% endblock main %}

templates/blog/blog.html
{% extends 'base.html' %} {% load static %}
{% load blog_extras %} {% load comments_extra %}
{% block main %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/layout.css' %}">
    <!-- Page Title
   ================================================== -->
    <div id="page-title">

        <div class="row">

            <div class="ten columns centered text-center">
                <h1>{{ user }}的个人博客</h1>

                <p>The sooner you start to code, the longer the program will take. —— Roy Carlson </p>
            </div>

        </div>

    </div>
    <!-- Page Title End-->
    <!-- Content
       ================================================== -->
    <div class="content-outer">
        <div id="page-content" class="row">

            <div id="primary" class="eight columns">
                {% for post in post_list %}
                    <article class="post">

                        <div class="entry-header cf">
                            <h1><a href="{{ post.get_absolute_url }}" title="">{{ post.title }}</a></h1>

                            <p class="post-meta">

                                <time class="date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                                /
                                <span class="categories">
                                    <a class="badge badge-pill badge-primary"
                                       href="{% url 'blog:category' post.category.id %}">{{ post.category }}</a> /
                                </span>
                            </p>
                        </div>

                        <div class="post-thumb">
                            <a href="{{ post.get_absolute_url }}" title="">
                                <img id="random-image"
                                     src="https://source.unsplash.com/collection/220381/1300x500"
                                     alt=""
                                     title="post-image"></a>
                        </div>

                        <div class="post-content">
                            <p>{{ post.excerpt }}</p>
                        </div>
                    </article>
                    <!-- post end -->
                {% endfor %}

                <!-- Pagination -->
                <nav class="col full pagination">
                    <!-- 如果不是第一页，则显示上翻按钮 -->
                    <ul>
                        {% if post_list.has_previous %}
                            <li>
                                <a class="page-numbers prev inactive" href="?page=1">
                                    &laquo; 1
                                </a>
                            </li>
                            <span>...</span>
                            <li>
                                <a href="?page={{ post_list.previous_page_number }}" class="page-numbers">
                                    {{ post_list.previous_page_number }}
                                </a>
                            </li>
                        {% endif %}

                        <li>
                            <!-- 当前页面 -->
                            <a href="#" class="page-numbers current">{{ post_list.number }}</a>
                        </li>

                        <!-- 如果不是最末页，则显示下翻按钮 -->
                        {% if post_list.has_next %}
                            <li>
                                <a href="?page={{ post_list.next_page_number }}"
                                   class="page-numbers"
                                >
                                    {{ post_list.next_page_number }}
                                </a>
                            </li>
                            <span>...</span>
                            <li>
                                <a href="?page={{ post_list.paginator.num_pages }}"
                                   class="page-numbers next"
                                >
                                    {{ post_list.paginator.num_pages }} &raquo;
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            </div>
            <!-- Primary End-->

            <div id="secondary" class="four columns end">

                <aside id="sidebar">

                    <div class="widget widget_search">
                        <h5>Search</h5>
                        <form action="#">

                            <input class="text-search" type="text"
                                   onfocus="if (this.value == 'Search here...') { this.value = ''; }"
                                   onblur="if(this.value == '') { this.value = 'Search here...'; }"
                                   value="Search here...">
                            <input type="submit" class="submit-search" value="">

                        </form>
                    </div>

                </aside>

            </div>
            <!-- Secondary End-->

        </div>

    </div>
    <!-- Content End-->

{% endblock main %}
{% block script %}{% endblock script %}

templates/blog/detail.html
{% extends 'base.html' %} {% load static %} {% load blog_extras %} {% load comments_extra %} {% block main %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">
<!-- Page Title
           ================================================== -->
<div id="page-title">

    <div class="row">

        <div class="ten columns centered text-center">
            <h1>{{ post.author }}发布的个人博客<span>.</span></h1>

            <p>The sooner you start to code, the longer the program will take. —— Roy Carlson </p>
        </div>

    </div>

</div>
<!-- Page Title End-->


<!-- Content
           ================================================== -->
<div class="content-outer">

    <div id="page-content" class="row">

        <div id="primary" class="eight columns">

            <article class="post">

                <div class="entry-header cf">

                    <h1>{{ post.title }}</h1>

                    <p class="post-meta">
                        <time class="date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                        <span class="readings">
                                <a class="badge badge-pill badge-success"
                                   href="{{ post.get_absolute_url }}">阅读量: {{ post.views }}</a>
                            </span>
                        <br>
                        <span class="dauthor">
                                文章作者: {{ post.author }} /
                                <a class="badge badge-pill badge-info"
                                   href="{% url 'blog:post_update' post.id %}">更新文章</a>

                                <a class="badge badge-pill badge-danger" href="#"
                                   onclick="confirm_safe_delete()">删除文章</a>
                            </span>
                        <br>
                        <span class="categories">文章分类:
                                <a href="{% url 'blog:category' post.category.pk %}"
                                   class="badge badge-pill badge-primary">{{ post.category.name }}</a>
                            </span>
                        <br>
                        <span class="tags">
                                文章标签: {% show_related_tags post %}
                            </span>
                    </p>

                    <!-- hidden form for submit safe_delete -->
                    <form action="{% url 'blog:post_safe_delete' post.id %}" id="safe_delete" method="POST" style="display: none">
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                </div>

                <div class="post-thumb">
                    <img src="https://source.unsplash.com/collection/220381/1300x500" alt="post-image" title="post-image">
                </div>

                <div class="post-content">
                    {{ post.body |safe }}

                    <div class="bio cf">

                        <div class="gravatar">
                            <img src="{% static 'blog/images/author-img.png' %}" alt="">
                        </div>
                        <div class="about">
                            <h5><a title="Posts by {{ post.author }}" href="#" rel="author">{{ post.author }}</a>
                            </h5>
                            <p>暂无介绍</p>
                        </div>

                    </div>

                    <ul class="post-nav cf">
                        <li class="prev"><a rel="prev" href="#"><strong>上一篇</strong> Todo pre
                                Amet Nibh Vulputate</a></li>
                        <li class="next"><a rel="next" href="#"><strong>下一篇</strong> Todo next
                                Ipsum</a></li>
                    </ul>

                </div>

            </article>
            <!-- post end -->

            <!-- Comments
                ================================================== -->

            {% show_comments post user %}

            <!-- Comments End -->
        </div>

        <!-- 侧边栏开发 -->
        <div id="secondary" class="four columns end">

            <aside id="sidebar">

                <div class="widget widget_search">
                    <h5>Search</h5>
                    <form action="#">

                        <input class="text-search" type="text" onfocus="if (this.value == 'Search here...') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Search here...'; }" value="Search here...">
                        <input type="submit" class="submit-search" value="">

                    </form>
                </div>


                <div class="widget widget_text">
                    {% if post.toc %}
                    <h5 class="widget-title">文章目录</h5>
                    <div id="texttoc" class="textwidget">{{ post.toc|safe }}</div>
                    <script type="text/javascript">
                        var obj = document.getElementById("texttoc").innerHTML;
                        obj = '<ul>' + obj + '</ul>'
                        document.getElementById("texttoc").innerHTML = obj;
                    </script>
                    {% else %}
                    <h5 class="widget-title">Tenet</h5>
                    <div class="textwidget">When in doubt, use brute force. ——Ken Thompson</div>

                    {% endif %}

                </div>

                <!-- 显示最近发布的5篇博客 -->
                {% show_recent_posts 5 %}

                <!-- 显示博客归档 -->
                {% show_archives %}

                <!-- 显示所有的博客分类以及每个分类下的文章数 -->
                {% show_categories %}

                <!-- 显示所有的标签 -->
                {% show_tags %}

            </aside>
            <!-- Sidebar End -->

        </div>

    </div>

</div>
<!-- Content End-->


{% block script %}
<!-- ckeditor auto fit width -->
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>

<script>
    // 加载 modal
    function load_modal(post_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = `<iframe src="/comments/post-comment/${post_id}/${comment_id}" frameborder="0" style="width: 100%; height: 100%;"></iframe>`;
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    };

    // 处理二级回复
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'blog:detail' post.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>
{% endblock script %}

<script>
    // 安全删除的弹窗确认
    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗?",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>

{% endblock main %}

templates/blog/post.html
{% extends 'base.html' %} {% load static %}
{% block main %}
    <!-- Page Title
   ================================================== -->
    <div id="page-title">

        <div class="row">

            <div class="ten columns centered text-center">
                <h1>发布文章</h1>
                <p>又要开启新的创作了吗?</p>
            </div>

        </div>

    </div>
    <!-- Page Title End-->

    <!-- Content
    ================================================== -->
    <div class="content-outer">

        <div id="page-content" class="row page">

            <div id="primary" class="eight columns">

                <section>

                    <h1>文章内容</h1>

                    <div id="contact-form">
                        <!-- form -->
                        <form name="contactForm" id="contactForm" method="post" action="{% url 'blog:post_create' %}">
                            {% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <label for="{{ post_form.title.id_for_label }}">{{ post_form.title.label }}
                                        <span class="required">*</span></label>
                                    {{ post_form.title }} {{ post_form.title.errors }}
                                </div>

                                <div class="form-group">
                                    <label for="category">分类
                                        <span class="required">*</span>
                                        <span style="color: #838C95">(输入/选择)</span>
                                    </label>

                                    <select id="categories" class="easyui-combobox" name="category">
                                        <option value="none" disabled="disabled">输入/选择已有分类</option>
                                        {% for category in categories %}
                                            <option value="{{ category.id }}">{{ category }}</option>
                                        {% endfor %}
                                    </select>

                                </div>

                                <div class="form-group">
                                    <label for="{{ post_form.body.label }}">{{ post_form.body.label }}
                                        <span class="required">*</span></label>
                                    {{ post_form.body }} {{ post_form.body.errors }}
                                </div>

                                <div>
                                    <button class="submit">提交</button>
                                    <span id="image-loader">
                              <img src="{% static 'blog/images/loader.gif' %}" alt=""/>
                           </span>
                                </div>

                            </fieldset>
                        </form>
                        <!-- Form End -->

                        <!-- contact-warning -->
                        <div id="message-warning"></div>
                        <!-- contact-success -->
                        <div id="message-success">
                            <i class="icon-ok"></i>发布成功!<br/>
                        </div>
                    </div>

                </section>
                <!-- section end -->

            </div>

            <div id="secondary" class="four columns end">

                <aside id="sidebar">

                    <div class="widget widget_text">
                        {% if post.toc %}
                            <h5 class="widget-title">文章目录</h5>
                            <div class="textwidget">{{ post.toc|safe }}</div>
                        {% else %}
                            <h5 class="widget-title">Tenet</h5>
                            <div class="textwidget">When in doubt, use brute force. ——Ken Thompson</div>

                        {% endif %}

                    </div>

                    {#                    <div class="widget widget_contact">#}
                    {#                        <h5>Address and Phone</h5>#}
                    {#                        <p class="address">#}
                    {#                            山东省 威海市<br> 哈尔滨工业大学（威海） <br>#}
                    {#                            <span> 18xxxxxxx33  </span>#}
                    {#                        </p>#}
                    {##}
                    {#                        <h5>Email and Social</h5>#}
                    {#                        <p>#}
                    {#                            E-mail: 1223987303@qq.com<br> Github: <a href="https://github.com/M010K">@Github</a><br>#}
                    {#                            CSDN: <a href="https://blog.csdn.net/qq_43444349">M010K的博客</a>#}
                    {#                        </p>#}
                    {#                    </div>#}

                </aside>

            </div>
            <!-- secondary End-->

        </div>

    </div>
    <!-- Content End-->

{% endblock main %}