blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blog/<int:author_id>', views.blog_index, name='blog_index'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('post-create/', views.post_modify, name='post_create'),
    path('post-update/<int:id>/', views.post_modify, name='post_update'),
    path('post-safe-delete/<int:id>/', views.post_safe_delete, name='post_safe_delete'),
    path('about.html', views.about, name='about'),
    path('contact.html', views.contact, name='contact'),
    path('styles.html', views.feature, name='feature'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path("login/", views.user_login, name='login'),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.user_register, name="register"),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

templates/base.html
{% load static %} {% load blog_extras %}
<!DOCTYPE html>

<head>
    <!--- Basic Page Needs
   ================================================== -->
    <meta charset="utf-8">
    {% if user %}
        <title>{{ user }}的个人博客</title>
    {% else %}
        <title>M010K的个人博客</title>
    {% endif %}
    <meta name="description" content="基于HTML5/CSS3的个人博客">
    <meta name="author" content="M010K">

    <!-- Mobile Specific Metas
   ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'blog/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/media-queries.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/table_css/table.css' %}">

    <!-- 添加代码高亮样式 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11.0.1/styles/stackoverflow-light.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-easyui@1.5.21/css/easyui.css">


    <!-- Script
   ================================================== -->
    <script src="https://cdn.jsdelivr.net/npm/npm-modernizr@2.8.3/modernizr.min.js"></script>


    <!-- Favicons
	================================================== -->
    <link rel="shortcut icon" href="{% static 'blog/images/favicon.ico' %}">


</head>

<body>
<!-- 引入导航栏 -->
{% include 'header.html' %} {% block main %} {% endblock main %}

<!-- Call-To-Action Section
================================================== -->
<section id="call-to-action">

    <div class="row">

        <div class="eight columns offset-1">

            <h1><a href="https://github.com/M010K/Django_Blog">探索更多内容</a></h1>
            <p>这个站点主要用来管理发布的博客，如需要访问其他内容，欢迎访问我的Github👏.
                <!-- Simply type	the promocode in the box labeled “Promo Code” when placing your order. -->.
            </p>

        </div>

        <div class="three columns action">


        </div>

    </div>

</section>
<!-- Call-To-Action Section End-->

<!-- Github Section
================================================== -->
<section id="github">

    <div class="row">

        <div class="github-icon align-center">
            <i class="fa fa-github" href="https://github.com/M010K"></i>
        </div>

        <ul id="githuber" class="align-center">
                <span>
                    This is My Github Site.
                    <a href="https://github.com/M010K">https://github.com/M010K</a>
                </span>
        </ul>

        <p class="align-center"><a href="https://github.com/M010K" class="button">Follow HIM</a></p>

    </div>

</section>
<!-- Github Section End-->


<!-- 引入注脚 -->
{% include 'footer.html' %}

<!-- Java Script
================================================== -->
<script src="{% static 'blog/css/table_css/wrap_table.js' %}"></script>

<script>
    window.MathJax = {
        tex: {
            inlineMath: [
                ['$', '$'],
                ['\\(', '\\)']
            ]
        }
    };
</script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-migrate@3.3.2/dist/jquery-migrate.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.easyui@1.0.0/jquery.easyui.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flexslider@2.7.2/jquery.flexslider.min.js"></script>

{% block script %}{% endblock script %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>



<script src="{% static 'blog/js/doubletaptogo.js' %}"></script>
<script src="{% static 'blog/js/init.js' %}"></script>

<!-- code highlight -->
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.0.0/build/highlight.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
</script>

<!-- 引入layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>

</body>

</html>

templates/base_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reset Password</title>

    <!-- Font Icon -->
    <link rel="stylesheet"
          href="{% static 'userprofile/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'userprofile/css/style.css' %}">
</head>
<body>

<div class="main">
    <!-- Base Form -->
    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="{% static 'userprofile/images/signin-image.jpg' %}" alt="sing up image"></figure>
                </div>

                <div class="signin-form">
                    <h2 class="form-title">{% block title %} {% endblock title %}</h2>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {% block content %}{% endblock content %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>


<!-- JS -->
<script src="{% static 'userprofile/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'userprofile/js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/footer.html
<!-- footer
================================================== -->
<footer>

    <div class="row">

        <div class="twelve columns">
            <ul class="footer-nav">
                <li><a href="{% url 'blog:index' %}">Home.</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'blog:blog_index' user.id %}">Blog.</a></li>
                {% else %}
                    <li><a href="#">Blog.</a></li>
                {% endif %}

                <!-- <li><a href="portfolio-index.html">Portfolio.</a></li> -->
                <li><a href="{% url 'blog:about' %}">About.</a></li>
                <li><a href="{% url 'blog:contact' %}">Contact.</a></li>
                <li><a href="{% url 'blog:about' %}">Features.</a></li>
            </ul>

{#            <ul class="footer-social">#}
{#                <li><a href="#"><i class="fa fa-facebook"></i></a></li>#}
{#                <li><a href="#"><i class="fa fa-twitter"></i></a></li>#}
{#                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>#}
{#                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>#}
{#                <li><a href="#"><i class="fa fa-skype"></i></a></li>#}
{#                <li><a href="#"><i class="fa fa-rss"></i></a></li>#}
{#            </ul>#}

            <ul class="copyright">
                <li>Copyright &copy; 2021 M010K</li>
            </ul>

        </div>

        <div id="go-top" style="display: block;"><a title="Back to Top" href="#">Go To Top</a></div>

    </div>

</footer>
<!-- Footer End-->

templates/header.html
{% load static %}
<!-- Header
================================================== -->
<header>

    <div class="row">

        <div class="twelve columns">

            <div class="logo">
                <a href="{% url 'blog:index' %}"><img alt="" src="{% static 'blog/images/logo.png' %}"></a>
            </div>

            <nav id="nav-wrap">

                <a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show navigation</a>
                <a class="mobile-btn" href="#" title="Hide navigation">Hide navigation</a>

                <ul id="nav" class="nav">

                    <li class="current"><a href="{% url 'blog:index' %}">Home</a></li>
                    <li><span><a href="#">Blog</a></span>
                        <ul>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'blog:blog_index' user.id %}">{{ user }}'s Blog</a></li>
                            {% else %}
                            <li><a href="#">Blog Index</a></li>
                            {% endif %}
                            <li><a href="{% url 'blog:post_create' %}">Post</a></li>
                        </ul>
                    </li>
                    <!-- <li><span><a href="portfolio-index.html">Portfolio</a></span>
                <ul>
                    <li><a href="portfolio-index.html">Portfolio Index</a></li>
                    <li><a href="portfolio.html">Portfolio Entry</a></li>
                </ul>
            </li> -->
                    <li><a href="{% url 'blog:about' %}">About</a></li>
                    <li><a href="{% url 'blog:contact' %}">Contact</a></li>
                    <li><a href="{% url 'blog:feature' %}">Features</a></li>

                    {% if user.is_authenticated %}
                        <li><span><a href="#">{{ user.username }}</a></span>
                            <ul>
                                <li><a href="#" onclick="user_delete()">Delete Account</a></li>
                                <li><a href="{% url "userprofile:logout" %}">Log Out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'userprofile:login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <!-- end #nav -->

            </nav>
            <!-- end #nav-wrap -->

        </div>

    </div>

    {% if user.is_authenticated %}
        <form
                style="display:none;"
                id="user_delete"
                action="{% url 'userprofile:delete' user.id %}"
                method="POST"
        >
            {% csrf_token %}
            <button type="submit">发送</button>
        </form>
        <script>
            function user_delete() {
                // 调用layer弹窗组件
                layer.open({
                    title: "确认删除",
                    content: "确认删除用户资料吗？",
                    yes: function (index, layero) {
                        $('form#user_delete button').click();
                        layer.close(index);
                    },
                })
            }
        </script>
    {% endif %}

</header>
<!-- Header End -->