blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blog/<int:author_id>', views.blog_index, name='blog_index'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('post-create/', views.post_modify, name='post_create'),
    path('post-update/<int:id>/', views.post_modify, name='post_update'),
    path('post-safe-delete/<int:id>/', views.post_safe_delete, name='post_safe_delete'),
    path('about.html', views.about, name='about'),
    path('contact.html', views.contact, name='contact'),
    path('styles.html', views.feature, name='feature'),
]

comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'

urlpatterns = [
    path('post-comment/<int:post_id>', views.post_comment, name="post_comment"),
    path('post-comment/<int:post_id>/<int:parent_comment_id>', views.post_comment, name="comment_reply"),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path("login/", views.user_login, name='login'),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.user_register, name="register"),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

comments/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models

from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.


class Comment(MPTTModel):
    post = models.ForeignKey(
        'blog.Post',
        on_delete=models.CASCADE,
        related_name='comments'
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    body = RichTextField()
    created_time = models.DateTimeField(auto_now_add=True)

    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    # 新增，记录二级评论回复给谁, str
    reply_to = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='replyers'
    )

    class MPTTMeta:
        order_insertion_by = ['created_time']

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.body[:20]

comments/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

comments/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from blog.models import Post
from .models import Comment
from .forms import CommentForm


@login_required(login_url='/userprofile/login/')
def post_comment(request, post_id, parent_comment_id=None):
    # 检查用户是否具有评论权限
    if not request.user.has_perm('comments.add_comment'):
        return HttpResponse("抱歉!你无权发布评论!具体请在主页联系M010K!")

    post = get_object_or_404(Post, id=post_id)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user

            # 二级回复
            if parent_comment_id:
                parent_comment = Comment.objects.get(id=parent_comment_id)
                # 若回复层级超过二级，则转换为二级
                new_comment.parent_id = parent_comment.get_root().id
                # 被回复人
                new_comment.reply_to = parent_comment.user
                new_comment.save()
                # return HttpResponse('200 OK')
                return JsonResponse({"code": "200 OK", "new_comment_id": new_comment.id})

            new_comment.save()
            return redirect(post)
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    elif request.method == "GET":
        comment_form = CommentForm()
        context = {
            'comment_form': comment_form,
            'post_id': post_id,
            'parent_comment_id': parent_comment_id
        }
        return render(request, 'comments/reply.html', context)
    # 处理错误请求
    else:
        return HttpResponse("仅接受GET/POST请求。")

templates/comments/inclusions/_list.html
{% load static %} {% load mptt_tags %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

{% if user.is_authenticated %}
    <div>
        <form
                action="{% url 'comments:post_comment' post.id %}"
                method="POST"
        >
            {% csrf_token %}
            <div class="form-group">
                <label for="body"><h3>发布评论：</h3></label>
                <div>
                    {{ comment_form.media }}
                    {{ comment_form.body }}
                </div>
            </div>
            <!-- 提交按钮 -->
            <button type="submit" class="btn btn-primary " style="padding: 12px 24px; font-size: 100%;">发送</button>
        </form>
    </div>
    <br>
{% else %}
    <br>
    <h5 class="row justify-content-center">
        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
    </h5>
    <br>
{% endif %}


<div id="comments">
    {% load mptt_tags %}
    <h3>评论列表，共 <span>{{ comments_list.count }}</span> 条评论</h3>
    <!-- commentlist -->
    <div class="commentlist">
        <!-- 遍历树形结构 -->
        {% recursetree comments_list %}
            {% with comment=node %}
                {% if comment.is_root_node %}
                    <li class="depth-1">
                        <!-- parent comment -->
                        <div class="avatar">
                            <img class="avatar" src="{% static 'blog/images/user-01.png' %}" alt="" width="50"
                                 height="50">
                        </div>
                        <div class="comment-info">
                            <cite>{{ comment.user }}</cite>

                            <div class="comment-meta">
                                <time class="comment-time"
                                      datetime="{{ comment.created_time|date:"Y-m-d H:i" }}">{{ comment.created_time|date:"Y-m-d H:i" }}</time>
                                <span class="sep">/</span>

                                <!-- 加载 modal 的按钮 -->
                                {% if user.is_authenticated %}
                                    <button type="button"
                                            class="submit"
                                            style="padding: 2px 24px; font-size: 100%;"
                                            onclick="load_modal({{ post.id }}, {{ comment.id }})"
                                    >
                                        回复
                                    </button>
                                {% else %}
                                    <a class="reply" href="{% url 'userprofile:login' %}">Reply</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="comment-text">
                            <p>{{ comment.body | safe |linebreaks }}</p>
                        </div>

                        <!-- Modal -->
                        <div class="modal fade"
                             id="comment_{{ comment.id }}"
                             tabindex="-1"
                             role="dialog"
                             aria-labelledby="CommentModalCenter"
                             aria-hidden="true"
                        >
                            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                <div class="modal-content" style="height: 480px">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                    </div>
                                    <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                </div>
                            </div>
                        </div>

                        {% if comment.get_descendants.count > 0 %}
                            <ol class="commentlist">
                                {% for child_comment in comment.get_descendants %}
                                    <li class="depth-2">
                                        <!-- child comment -->
                                        <div class="avatar">
                                            <img class="avatar" src="{% static 'blog/images/user-02.png' %}" alt=""
                                                 width="50"
                                                 height="50">
                                        </div>
                                        <div class="comment-info">
                                            <cite>{{ child_comment.user }}</cite>

                                            <div class="comment-meta">
                                                <time class="comment-time"
                                                      datetime="{{ child_comment.created_time|date:"Y-m-d H:i" }}">{{ child_comment.created_time|date:"Y-m-d H:i" }}</time>
                                                <span class="sep">/</span>

                                                <!-- 加载 modal 的按钮 -->
                                                {% if user.is_authenticated %}
                                                    <button class="submit"
                                                            onclick="load_modal({{ post.id }}, {{ child_comment.id }})"
                                                            style="padding: 2px 24px; font-size: 100%;"
                                                            type="button"
                                                    >
                                                        回复
                                                    </button>
                                                {% else %}
                                                    <a class="reply" href="{% url 'userprofile:login' %}">Reply</a>
                                                {% endif %}
                                            </div>
                                        </div>

                                        <!-- 显示被回复人 -->
                                        {% if child_comment.reply_to %}
                                            <i class="far fa-arrow-alt-circle-right"
                                               style="color: cornflowerblue;"
                                            ></i>
                                            <strong style="color: pink">
                                                @ {{ child_comment.reply_to }}
                                            </strong>
                                        {% endif %}

                                        <div class="comment-text">
                                            <p>{{ child_comment.body |safe | linebreaks }}</p>
                                        </div>

                                        <!-- Modal -->
                                        <div class="modal fade"
                                             id="comment_{{ child_comment.id }}"
                                             tabindex="-1"
                                             role="dialog"
                                             aria-labelledby="CommentModalCenter"
                                             aria-hidden="true"
                                        >
                                            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                                <div class="modal-content" style="height: 480px">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalCenterTitle">
                                                            回复 {{ child_comment.user }}：</h5>
                                                    </div>
                                                    <div class="modal-body"
                                                         id="modal_body_{{ child_comment.id }}"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ol>
                        {% endif %}
                    </li>
                {% endif %}


            {% endwith %}
        {% endrecursetree %}
    </div>

</div>

<!-- reset css style -->
<link rel="stylesheet" href="{% static 'blog/css/default.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/layout.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/media-queries.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/table_css/table.css' %}">


<script>
    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = `<iframe src="/comments/post-comment/${article_id}/${comment_id}" frameborder="0" style="width: 100%; height: 100%;" id="iframe_${comment_id}"></iframe>`;
            $(modal_body).append(content);
        }

        $(modal_id).modal('show');
    }

    // 处理二级回复
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'blog:detail' post.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>

templates/comments/inclusions/_total_comments.html
<h2 align="cneter">累计评论</h2>
<p>共 {{ comment_count }} 条</p>