blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blog/<int:author_id>', views.blog_index, name='blog_index'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('post-create/', views.post_modify, name='post_create'),
    path('post-update/<int:id>/', views.post_modify, name='post_update'),
    path('post-safe-delete/<int:id>/', views.post_safe_delete, name='post_safe_delete'),
    path('about.html', views.about, name='about'),
    path('contact.html', views.contact, name='contact'),
    path('styles.html', views.feature, name='feature'),
]

blog/models.py
import markdown
from django.utils.html import strip_tags

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    """
    博客的分类模型
    """
    name = models.CharField(max_length=100)
    # 分类摘要
    excerpt = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    博客的标签模型
    """
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    博客的文章模型
    """

    # 文章标题
    title = models.CharField('标题', max_length=70)

    # 文章正文，使用 TextField 来存储大段文本。
    body = models.TextField('正文')

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')

    # 文章摘要
    excerpt = models.CharField('摘要', max_length=200, blank=True)

    # 文章分类与标签，分类与标签的模型已经定义在上面
    category = models.ForeignKey(
        Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是
    # django 为我们已经写好的用户模型。
    author = models.ForeignKey(
        User, verbose_name='作者', on_delete=models.CASCADE)

    # 新增 views 字段记录阅读量
    # editable=False表示不允许通过后台设置这一数据
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        """
        :param args:
        :param kwargs:
        修改文章时更新modified_time
        """
        self.modified_time = timezone.now()

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """
        返回博客详情页的绝对url
        """
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        """
        将访问次数加一并更新数据库
        """
        self.views += 1
        self.save(update_fields=['views'])

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    """
    博客文章对应的表单类
    """

    class Meta:
        model = Post
        fields = ['title', 'body']  # 定义表单包含的字段

blog/views.py
import re

import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension, slugify

from .forms import PostForm
from .models import Category, Tag, Post


# Create your views here.
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 3
    ordering = ['-created_time']

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['post_list'] = Post.objects.all()
        context['category_list'] = Category.objects.all().order_by('-id')
        return context


@login_required(login_url='/userprofile/login')
def blog_index(request, author_id=None):
    if author_id:
        post_list = Post.objects.filter(author_id=author_id)
    else:
        post_list = Post.objects.all().order_by('-created_time')

    paginator = Paginator(post_list.order_by('-created_time'), 3)
    page = request.GET.get('page')

    post_list = paginator.get_page(page)

    return render(request, 'blog/blog.html', context={"post_list": post_list})


class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 3

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        self.object_list = Post.objects.filter(category_id=cate.id)
        context = super().get_context_data(**kwargs)
        return context


class TagView(ListView):
    model = Tag
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        temp_tags = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return Post.objects.filter(tags=temp_tags)


class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，需要将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),

            'pymdownx.arithmatex',  # 使用Mathjax渲染网页
        ])
        post.body = md.convert(post.body)

        # 判断是否有目录结构
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''

        return post


@login_required(login_url='/userprofile/login')
def post_modify(request, id=None):
    # 判断用户是否请求提交数据
    if not request.user.has_perm('blog.add_post'):
        return HttpResponse("抱歉!你无权发布文章!具体请在主页联系M010K!")

    if request.method == "POST":
        post_form = PostForm(data=request.POST)

        # 判断用户提交的数据是否合法
        if post_form.is_valid():
            # 判断是更新还是新建文章
            if id:
                post = Post.objects.get(id=id)
                if request.user != post.author:
                    return HttpResponse("抱歉!你不是本文的作者，无权修改本文!")
                post.title = request.POST['title']
                post.body = request.POST['body']
            else:
                post = post_form.save(commit=False)
                post.author = request.user

            cate_id = request.POST['category']
            if not cate_id:
                return HttpResponse("文章分类不能为空!")

            if str(cate_id).isdigit():    # 文章分类为整数
                cate = Category.objects.get(id=cate_id)
                if cate:    # 是已有的文章分类
                    post.category = Category.objects.get(id=request.POST['category'])
                else:   # 文章分类名字为数字，创建对应分类
                    post.category = Category.objects.create(name=cate_id)
            else:   # 文章分类名字不是纯数字，创建对应分类
                post.category = Category.objects.create(name=cate_id)

            post.save()

            return redirect("blog:index")  # 发布完成后返回到Home页面
        # 用户请求获取数据
    else:
        post_form = PostForm()
        categories = Category.objects.all()
        tags = Tag.objects.all()
        context = {
            "post": Post.objects.get(id=id) if id else None,
            "post_form": post_form,
            "categories": categories,
            "tags": tags
        }

        if id:
            return render(request, 'blog/post_update.html', context=context)
        else:
            return render(request, 'blog/post.html', context=context)


@login_required(login_url='/userprofile/login')
def post_safe_delete(request, id):
    if request.method == "POST":
        post = Post.objects.get(id=id)
        if request.user != post.author:
            return HttpResponse("抱歉!你不是本文的作者，无权删除本文!")
        post.delete()
        return redirect('blog:index')
    else:
        return HttpResponse("删除文章仅允许Post请求!")


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    return render(request, 'blog/contact.html')


def feature(request):
    return render(request, 'blog/styles.html')


def archive(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

templates/blog/inclusions/_archives.html
<div class="widget widget_archives">
    <h5 class="widget-title">归档</h5>
    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:archive' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月<span class="post-count">({{ date.num_posts }})</a>
        </li>
        {% empty %} 暂无归档！ {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget_categories">
    <h5 class="widget-title">分类</h5>
    <ul>
        {% for category in category_list %}
        <li>
            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
        </li>
        {% empty %} 暂无分类！ {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_index_categories.html
<!--
<script>
    function addRandomURL() {
        var img_list = {
            'img1': 'https://source.unsplash.com/collection/220381/600x626',
            'img2': 'https://source.unsplash.com/collection/1041983/600x626',
            'img3': 'https://source.unsplash.com/collection/9042799/600x626',
            'img4': 'https://source.unsplash.com/collection/1198107/600x626',
            'img5': 'https://source.unsplash.com/collection/3694365/600x626',
            'img6': 'https://source.unsplash.com/collection/1708734/600x626',
            'img7': 'https://source.unsplash.com/collection/1118894/600x626',
            'img8': 'https://source.unsplash.com/collection/388793/600x626',
            'img9': 'https://source.unsplash.com/collection/3150958/600x626',
            'img10': 'https://source.unsplash.com/collection/894/600x626',
        }
        var path = ''
        var x = Math.floor((Math.random() * 10) + 1);
        path = "img" + x;

        var obj = document.getElementById("random-image");
        obj.src = img_list[path];
        obj.id = "random-image" + x.toString() + Math.floor((Math.random() * 10000) + 1);
    }
</script>
-->

<div id="portfolio-wrapper" class="bgrid-quarters s-bgrid-halves">
    {% for category in category_list %}
        <div class="columns portfolio-item">
            <div class="item-wrap">
                <a href="{% url 'blog:category' category.pk %}">

                    <img id="random-image" alt="" src="https://source.unsplash.com/collection/3694365/600x626">

                    <div class="overlay"></div>
                    <div class="link-icon"><i class="fa fa-link"></i></div>
                </a>
                <div class="portfolio-item-meta">
                    <h5><a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a></h5>
                    <p>
                        {% if category.excerpt|length > 0 %} {{ category.excerpt }} {% else %} No discription of this
                            category. {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <!--
        <script type="text/javascript">
            addRandomURL()
        </script>
        -->
    {% empty %}
        <div class="columns portfolio-item">
            <div class="item-wrap">
                <a href="#">
                    <img alt="" src="https://source.unsplash.com/collection/220381/600x626">
                    <div class="overlay"></div>
                    <div class="link-icon"><i class="fa fa-link"></i></div>
                </a>
                <div class="portfolio-item-meta">
                    <h5><a href="#">Blank Category</a></h5>
                    <p>No discription of this category.</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h5 class="widget-title">最新文章</h5>
    <ul>
        {% for post in recent_post_list %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% empty %}
        <a href="#">暂无文章！</a> {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_related_tags.html
{% for tag in tag_list %}
    <a href="{% url 'blog:tag' tag.pk %}" class="badge badge-pill badge-secondary">{{ tag.name }}</a>
{% empty %}
    <a class="badge badge-pill badge-secondary" href="#">暂无标签</a> {% endfor %}

templates/blog/inclusions/_tags.html
<div class="widget widget_tag_cloud">
    <h5 class="widget-title">标签云</h5>
    <div class="tagcloud cf">
        {% for tag in tag_list %}
            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }} <span
                    class="post-count">({{ tag.num_posts }})</span></a> {% empty %} 暂无标签！ {% endfor %}
    </div>
</div>
</div>

templates/blog/inclusions/_total_views.html
<h2>累积访问量</h2>
{% if view_count.nums %}
    <p>{{ view_count.nums }} 次</p>
{% else %}
    <p> 0 次</p>
{% endif %}